### ISSUE TITLE
Winlogbeat default paths 

### ISSUE THREAD

**Issue by stephanbuys** [elastic/winlogbeat#2]
- At the moment eventbeat checks `/etc/eventbeat/eventbeat.yml` for configuration data.
  
  This probably requires a sane/safe folder for Windows (especially when the final executable gets run as a service).
   
- The `eventbeat.yml` file could also be updated to give "safe" default windows paths (eg. `file` default `path` is `/tmp/eventbeat`

**Comment by andrewkroh** [comment]
Regarding the first point. This is actually an issue across all Beats because it is the [default](https://github.com/elastic/libbeat/blob/master/cfgfile/cfgfile.go#L18) from libbeat. I would like to fix this but I am not sure what to make the default for Windows.

The `logger::file::path` parameter [defaults](https://github.com/elastic/libbeat/blob/master/logp/logp.go#L66) to `C:\\ProgramData\\eventbeat\\Logs` on Windows. So I think the config file just needs to be cleaned up which can now be done using the [scripts](https://github.com/elastic/libbeat/tree/master/scripts) contained in libbeat for updating each beat with the latest libbeat dependency, configuration template, etc.

**Comment by andrewkroh** [comment]
Opening until libbeat is updated.

**Comment by andrewkroh** [comment]
Summary:

- Configuration file defaults to `C:\Program Files\Winlogbeat\winlogbeat.yml`. #16
- Logging path defaults to `C:\ProgramData\winlogbeat\Logs` in the configuration file provided with the zip file from beats-packer. #15
